/LINK %/NOINIT/ /MAP:MAP %/SYMSEG:L/ %/SET:.LOW.:200/ SYS:STENEX.REL
/LIST/MACRO %/NOLOCALS/ %/CORE:80K/ DSK:TENDMP.10X
PROLOG.REL=PARAMS.AI+PROLOG/COMPILE
%/SET:.LOW.:RESMA0/ VERSIO.REL=VERSIO+SYSNAM
LDINIT.REL=LDINIT/COMPILE
%/LOCALS/SCHED.REL=SCHED
PAGEM.REL=PAGEM
PISRV.REL=PISRV
SWPMON.REL=SWPMON
FORKS.REL=FORKS
TTYSRV.REL=TTYSRV
IMPDV.REL=IMPDV
DSK.REL=DSK+DSKPAK
DRM.REL=DRMBRY
FILEDE.REL=PARAMS.AI+FILE/COMPILE
PSDOTY.REL=PSDOTY
DEVICE.REL=DEVICE
DIRECT
FREE
FUTILI
GTJFN
IO.REL=IO
JSYS.REL=JSYS
LOOKUP
DECTAP.REL=DECTAP
MAGTAP.REL=MAGTAP
DISC.REL=DISC
FILINI.REL=FILINI
FILTTY.REL=FILTTY
HOSTS.REL=HOSTS
LINEPR.REL=LINEPR
PDP15.REL=PDP15
TV.REL=TV
NETWRK.REL=NETWRK
NIL
PTP.REL=PTP
PTR.REL=PTR
STRING
%/SEGMENT:HIGH/ %/NOLOCALS/ MFLIN,MR,MFLOUT,DATIME
SYS:JOBDAT.REL
%/NOSYSLIB/ %/SEGMENT:LOW/ EDDT.10X
%/SEGMENT:DEFAULT/ POSTLD.REL=POSTLD
