		DIFFERENCES BETWEEN CLISP FOR EXPRESSIONS
		AND MASINTER FOR-EXPRESSIONS:




(1) IN EXPRESSIONS (FOR I FROM 1 TO (TIMES J 20) --) 
	CLISP RECOMPUTES (TIMES J 20) EACH TIME THRU THE LOOP;
	MASINTER-FOR'S WILL COMPUTE (TIMES J 20) ONCE AND SET
	A SPECIAL VARIABLE TO ITS VALUE --
	OR MORE GENERALLY, THE "TO" EXPRESSION" AND THE "BY"
	EXPRESSION , IF NOT A SIMPLE VARIABLE, WILL
	BE COMPUTED ONCE AND THE VALUE SAVED BEFORE THE LOOP IS
	ENTERED.

(2) CLISP HAS NO CONSTRUCT EXACTLY EQUIVALENT TO "IS" --
	SOME THINGS CAN BE ACCOMPLISHED BY SAYING
	... BIND I EACHTIME I_EXPR ...
INSTEAD OF ... AS I IS EXPR ...

(3) THIS ONE IS HARD TO EXPLAIN:  MASINTER FOR-EXPRESSIONS
	ARE VERY DEPENDENT ON THE ORDER OF THE "AS" AND "WHEN" CLAUSES..
	FOR EXAMPLE,
	(FOR I FROM 1 TO 10 WHEN I NEQ 5 AS X IN L DO (PRINT <X I>)
	IF X IS (A B C D E F G H I J K ...) WILL PRINT
	(A 1), (B 2), (C 3), (D 4), (E 6), (F 7) ...
	THE POINT IS THAT THE "WHEN" ONLY AFFECTS THE RANGE OF "I"
	AND NOT THAT OF "X". .. IN CLISP FOR-EXPRESSIONS,
	ALL "WHEN" CLAUSES ARE TESTED AFTER THE UPDATING OF ALL VARIABLES..

(4)  THERE ARE NO NESTED FOR-EXPRESSIONS IN CLISP.. I.E. YOU CANT SAY
   (FOR X IN L FOR Y IN X COLLECT Y)  TO "SPREAD" A LIST OF LISTS.


