LOBLI_START0,BEGIN,LOADDR,LODECL,LODRIV,LOGTRE,LOLEXA,LOLSTP,LOMACR,LOXREF,END
H1BLI_START1,BEGIN,H1CNTR,H1DECL,H1GTRE,H1LEXA,H1MACR,H1REQU,H1SYNT,END
H2BLI_START2,BEGIN,H2ADDR,H2ARIT,H2CNTR,H2GTRE,H2REGI,END
H3BLI_START3,BEGIN,H3PEEP,H3ASSY,H3CCL,H3CNTR,H3DECL,H3LDIN,H3LEXA,H3LSTP,H3REGI,H3XREF,H3DRIV,END
