;**TO MAKE F40.SHR FROM FILES EXEC.MAC,FX1.MAC,FX2.MAC,FX3.MAC,FX4.MAC
;
;**SUBMIT WITH COMMAND .QUEUE I:=F40/RESTART:1/TIME: 0:10:00
;
;**REQUIRED FILES:  (LATEST RELEASED VERSION)
;
;[10,7]	PIP.SHR
;	TECO.SHR
;	DIRECT.SHR
;	MACRO.SHR
;	LINK.SHR (AND ASSOCIATES)
;	JOBDAT.REL
;	RUNOFF.SHR
;
;[SELF]	EXEC.MAC
;	FX1.MAC
;	FX2.MAC
;	FX3.MAC
;	FX4.MAC
;
;**OUTPUT FILES
;
;	F40.SHR
;	F40.MAP
;	F40.LOG
;
;**MAKE A RECORD
;
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
;
;
A:.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=[10,7]PIP.SHR,TECO.SHR,DIRECT.SHR,MACRO.SHR,LNK???.SHR,JOBDAT.REL,RUNOFF.SHR
*TTY:/CHECKSUM=EXEC.MAC,FX1.MAC,FX2.MAC,FX3.MAC,FX4.MAC
*TTY:/CHECKSUM=F40???.*
;
;**READY TO GO
;
;
;**COMPILE ,LOAD AND SAVE MAKING MAP AND SHR FILES
;
.RUN DSK:TECO[10,7]
*EWREENTR.MAC
*IREENTR=0
EX
.RUN DSK:MACRO[10,7]
*EXEC,_REENTR,EXEC
.RUN DSK:MACRO[10,7]
*FX4,_REENTR,FX4
*FX3,_REENTR,FX1,FX2,FX3
;
.RUN DSK:LINK[10,7]
*F40.MAP/MAP
*EXEC,FX4,FX3/GO
.SSAVE DSK:F40
.VERSION
.IF (ERROR) .E 137
;
;TRY IT
;
.RUN DSK:TECO[10,7]
EWF40TST.F4
I	DIMENSION A(2)
10	I=2+3/(6-2)
	A(I+1)=(A(I)+4.567E23)/(A(I)**3.4+2.33E-4)
	1  +1.2
C A COMMENT
	GO TO 10
	END
EX
.RUN DSK:F40
,TTY:=F40TST
;
;**CHECKSUM DIRECTORY OF SAVE FILES
;
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=F40.SHR
;
;
.PRINT F40.MAP
;.PLEASE F40 SUCCESSFUL
;
;**GENERATE THE DOC FILE WITH FIELD IMAGE RUNOFF
;
.RUN DSK:RUNOFF[10,7]
*F40027.RND
;
;**DELETE ALL TEMPORARY FILES
;
%FIN: .RUN DSK:PIP[10,7]
DSK:/D=EXEC.REL,FX3.REL,FX4.REL,REENTR.MAC,F40TST.F4,F40???.LST,F40???.DOC
