;FOROTS.CTL	%4A.(406)	CONTROL FILE TO MAKE FOROTS.SHR AND
;				FORLIB.REL FOR THE KA AND KI
;
;*** COPYRIGHT 1974, DIGITAL EQUIPMENT CORP., MAYNARD, MASS. ***
;
;**SUBMIT WITH THE COMMAND  .QUEUE I:=FOROTS/RESTART:1/TIME:0:22:00
;
;**REQUIRED FILES:	(LASTEST VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	LINK.SHR AND ASSOCIATED HIGH SEGMENTS
;
;[SELF]
;		FORPRM.KA	;FORPRM FOR KA10
;		FORPRM.KI	;FORPRM FOR KI10
;	FORJAK.MAC		;REQUIRED UUO SIMULATION ONLY
;	FORINI.MAC
;	FOROTS.MAC
;	FORFUN.MAC		;LINK %2 OVERLAY FUNCTION MODULE
;	FORQUE.MAC
;	FORCNV.MAC
;	FORTRP.MAC
;	FORERR.MAC
;	FOROPN.MAC
;	FORXIT.MAC
;	FORDMP.MAC
;	FORPSE.MAC
;	FORPLT.MAC
;	FORCPX.MAC
;	FORSIN.MAC
;	FORDBL.MAC
;	FORDAR.MAC
;	FORRTF.MAC
;	FORMSC.MAC
;
;[OUTPUT]
;	FOROKA.SHR	FOROTS FOR KA10
;	FORLKA.REL	FORLIB FOR KA10
;	FOROKA.MAP	MAP FILE FOR KA10 FOROTS
;	FORLKA.GLB	GLOB FILE FOR KA10 FORLIB
;	FOROKI.SHR	FOROTS FOR KI10
;	FORLKI.REL	FORLIB FOR KI10
;	FOROKI.MAP	MAP FILE FOR KI10 FOROTS
;	FORLKI.GLB	GLOB FILE FOR KI10 FOROTS
;	FOROTS.LOG	LOG FILE OF THIS RUN
;
;FOR A KA10	FOROKA.SHR BECOMES FOROTS.SHR
;		FORLKA.REL BECOMES FORLIB.REL
;FOR A KA10	FOROKI.SHR BECOMES FOROTS.SHR
;		FORLKI.REL BECOMES FORLIB.REL
;
;
;**SET VERSION WATCH AND SET[10,7] AS LIBRARY 
;**ASSIGN DSK SYS TO ACCESS FILES FROM [10,7]
;
;
.SET WATCH VERSION
.RUN SETSRC[10,7]
*LIB[10,7]
*C DSKB,DSKC
*T
.AS DSK SYS
;
;**MAKE A RECORD OF CUSPS USED
;
.RUN DIRECT
*TTY:/CHECKSUM=[10,7]COMPIL.SHR,MACRO.SHR,DIRECT.SHR,SETSRC.SAV,GLOB.SHR
*TTY:/CHECKSUM=[10,7]LINK.SHR,LNK???.SHR
*TTY:/CHECKSUM_FOR???.MAC,FOROTS.CTL,FRS04A.RND,FOROTS.DOC,FRS04A.BWR
*TTY:/CHECKSUM=FORPRM.KA,FORPRM.KI
;
;
;
;
;**BUILD FOROTS FOR KA10
;
.COMP /MAC /COMP FORJAK
.COMP /MAC /COMP FORPRM.KA,FORINI,FOROTS,FORFUN,FORQUE,FORCNV,FORTRP
.COMP /MAC /COMP FORPRM.KA(PPP,),FORERR(PPP,)
.COMP /MAC /COMP FORPRM.KA,FOROPN,FORXIT,FORDMP,FORPSE,FORPLT,FORCPX,FORSIN,FORDBL,FORDAR,FORRTF,FORMSC
;
;MAKE FORLKA.REL
;
;
;
.RUN PIP
*FORLKA.REL=FORJAK.REL,FORINI.REL,FOROTS.REL,FORFUN.REL,FORQUE.REL
*FORLKA.REL=FORLKA.REL,FORCNV.REL,FORTRP.REL,FORERR.REL,FOROPN.REL
*FORLKA.REL=FORLKA.REL,FORDMP.REL,FORPSE.REL,FORPLT.REL,FORCPX.REL
*FORLKA.REL=FORLKA.REL,FORSIN.REL,FORDBL.REL,FORDAR.REL,FORRTF.REL
*FORLKA.REL=FORLKA.REL,FORMSC.REL,FORXIT.REL
;
;
;MAKE THE FOROKA.SHR MODULE
;
.RUN LINK
*FOROKA/MAP = FOROTS,FORLKA/S/GO
.SSAVE D:FOROTS
.VERSION
.COP FOROKA.SHR=FOROTS.SHR
;
;
;**CHECK SUM DIRECTORY OF FOROKA.SHR,FORLKA.REL
;
.RUN DIRECT
*TTY:/CHECKSUM=FOROKA.SHR,FORLKA.REL
;
;
;
;**MAKE THE GLOB LIST
;
.RUN GLOB
*FORLKA_FORLKA
;
;
;**DELETE ALL TEMP FILES
;
.RUN PIP
*DSK:/D=FORJAK.REL,FORPRM.REL,FORINI.REL,FOROTS.REL,FORFUN.REL
*DSK:/D=FORQUE.REL,FORCNV.REL,FORTRP.REL,FORERR.REL,FOROPN.REL
*DSK:/D=FORXIT.REL,FORDMP.REL,FORPSE.REL,FORPLT.REL,FORCPX.REL
*DSK:/D=FORSIN.REL,FORDBL.REL,FORDAR.REL,FORRTF.REL,FORMSC.REL
*DSK:/D=FOROTS.SHR,*.UNV
;
;**BUILD FOROTS FOR KI10
;
.COMP /MAC /COMP FORJAK
.COMP /MAC /COMP FORPRM.KI,FORINI,FOROTS,FORFUN,FORQUE,FORCNV,FORTRP
.COMP /MAC /COMP FORPRM.KI(PPP,),FORERR(PPP,)
.COMP /MAC /COMP FORPRM.KI,FOROPN,FORXIT,FORDMP,FORPSE,FORPLT,FORCPX,FORSIN,FORDBL,FORDAR,FORRTF,FORMSC
;
;MAKE FORLKI.REL
;
;
;
.RUN PIP
*FORLKI.REL=FORJAK.REL,FORINI.REL,FOROTS.REL,FORFUN.REL,FORQUE.REL
*FORLKI.REL=FORLKI.REL,FORCNV.REL,FORTRP.REL,FORERR.REL,FOROPN.REL
*FORLKI.REL=FORLKI.REL,FORDMP.REL,FORPSE.REL,FORPLT.REL,FORCPX.REL
*FORLKI.REL=FORLKI.REL,FORSIN.REL,FORDBL.REL,FORDAR.REL,FORRTF.REL
*FORLKI.REL=FORLKI.REL,FORMSC.REL,FORXIT.REL
;
;
;MAKE THE FOROKI.SHR MODULE
;
.RUN LINK
*FOROKI/MAP = FOROTS,FORLKI/S/GO
.SSAVE D:FOROTS
.VERSION
.COP FOROKI.SHR=FOROTS.SHR
;
;
;**CHECK SUM DIRECTORY OF FOROKI.SHR,FORLKI.REL
;
.RUN DIRECT
*TTY:/CHECKSUM=FOROKI.SHR,FORLKI.REL
;
;
;
;**MAKE THE GLOB LIST
;
.RUN GLOB
*FORLKI_FORLKI
;
;
;**DELETE ALL TEMP FILES
;
.RUN PIP
*DSK:/D=FORJAK.REL,FORPRM.REL,FORINI.REL,FOROTS.REL,FORFUN.REL
*DSK:/D=FORQUE.REL,FORCNV.REL,FORTRP.REL,FORERR.REL,FOROPN.REL
*DSK:/D=FORXIT.REL,FORDMP.REL,FORPSE.REL,FORPLT.REL,FORCPX.REL
*DSK:/D=FORSIN.REL,FORDBL.REL,FORDAR.REL,FORRTF.REL,FORMSC.REL
*DSK:/D=FOROTS.SHR,*.UNV
;
%FIN: .DEAS SYS
;
;
;[END OF FOROTS.CTL]
