
; JOB %1(02) TO MAKE HELPER.REL
;   SUBMIT WITH COMMAND     .QUEUE I:=HELPER/RESTART:1
;
; HELPER IS A SUBROUTINE USED TO OUTPUT HELP TEXTS
; (SYS:??????.HLP) ONTO DEVICE TTY.  IT IS ENTERED VIA A PUSHJ
; WITH THE SIXBIT MODULE NAME IN AC#1.  THE RETURN FROM
; HELPER IS TO THE LOCATION FOLLOWING THE PUSHJ.  HELPER
; REQUIRES TEN(10) LOCATIONS ON THE PUSH DOWN LIST ON WHICH 
; TO STORE  AND FROM WHICH TO
; RESTORE USER AC'S, JOB FIRST FREE INFORMATION, AND THE
; BUFFER HEADER FOR THE DISK FILE BEING READ.  DISK INPUT OF
; THE HELP TEXT IS ACCOMPLISHED ON CHANNEL 0.
;
; CALLING SEQUENCE:	MOVEI	AC1,SIXBIT MODULE NAME
;			PUSHJ	P,.HELPR
;	 		RETURN TO HERE
;
; REQUIRED FILES:	(LATEST RELEASED VERSIONS)
; [10,7]  PIP.SHR
;	  COMPIL.SHR
;	  JOBDAT.REL
;	  MACRO.SHR
;	  LOADER.SHR
;	  DIRECT.SHR
;	  CREF.SHR
;	  C.MAC
; [SELF]  HELPER.MAC
;	  HLR???.RND
;
; OUTPUT FILE
;	  HELPER.REL
;
; OUTPUT LISTINGS
;	  HELPER CREF LISTINGS
;	  HELPER.LOG
;	  HELPER.DOC
;
.SET WATCH VERSION
; COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7],LOADER.SHR[10,7]
*/X_DSK:JOBDAT.REL[10,7],CREF.SHR[10,7],C.MAC[10,7],DIRECT.SHR[10,7]
;
.ASSIGN DSK:SYS
;
; COMPILE--PRODUCING CREF FILE
.COMPILE /CREF C+HELPER
; MAKE SURE WE GOT A .REL FILE
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=HELPER.REL,HELPER.CTL,HELPER.MAC,C.MAC,JOBDAT.REL,HLR???.RND
;
; PRODUCE CREF LISTING
.ASSIGN DSK LPT
.CREF
.COPY HELPER.TMP=HLR???.RND
.RUN RUNOFF[10,7]
*HELPER.TMP
*HELPER.DOC
;
.DEASSIGN
.MOUNT DTA:HELPER/VID:'HELPER SUBMISSION TAPE'/WE
.IF (ERROR)  .GOTO NOTAP
.ZERO HELPER:
.LABEL HELPER:HELPER
.COPY HELPER:=HELPER.CTL,HELPER.MAC,HLR???.RND,HELPER.REL
.DIRECTORY HELPER:
.DEASSIGN
.PLEASE OPR - GET A DIRECTORY OF DTA:HELPER AND DISMOUNT 
NOTAP::
.PLEASE HELPER SUCCESSFUL
;
; REMOVE TEMP FILES
%FIN: .DEL MACRO.SHR,PIP.SHR,COMPIL.SHR,LOADER.SHR,JOBDAT.REL,CREF.SHR
.DELETE C.MAC,DIRECT.SHR,HELPER.TMP
.IF (ERROR)  ;DON'T CARE IF FAILED
.PRINT /DISP:RENAME HELPER.LST,HELPER.LOG/DISP:DELETE,/COPIES:3 HELPER.DOC
;
.K/F
