;JOB%1(17) TO MAKE JOBDAT.REL FROM JOBDAT.MAC
;SUBMIT WITH COMMAND  .QUEUE I:=JOBDAT/RESTART:1
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	CREF.SHR
;[SELF]	JOBDAT.MAC
;
;OUTPUT FILE:
;	JOBDAT.REL
;OUTPUT LISTINGS:
;	JOBDAT  CREF LISTING
;	JOBDAT.LOG
;
;
;COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7],CREF.SHR[10,7]
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SHR
.GOTO A
A:.RUN DSK: DIRECT[10,7]
*TTY:/CHECKSUM=*.MAC
.ASSIGN DSK: SYS:
;
;COMPILE; PRODUCING CREF FILE
.COMPILE /CREF /COMPILE JOBDAT.MAC
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=JOBDAT.REL
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.CREF
.PLEASE JOBDAT SUCCESSFUL
;
;REMOVE ALL TEMPORARY FILES
%FIN: .DELETE MACRO.SHR,CREF.SHR,COMPIL.SHR,PIP.SHR
