; MACRO.CTL VERSION NUMBER %50(272)	DMN
;
; REQUIRED FILES:  (LATEST RELEASED VERSIONS)
; [10,7] PIP.SHR
; 	 DIRECT.SHR
; 	 COMPIL.SHR
; 	 MACRO.SHR
;	 LINK-10
;	 HELPER.REL
; 	 CREF.SHR
; [SELF] MACRO.MAC (NEW)
;	 MACRO.HLP
; 
; OUTPUT FILES:
; 	 MACRO.SHR
; OUTPUT LISTINGS:
;	 MACRO.MAP
;	 MACRO   CREF LISTING
;	 MACRO.LOG
;
; GET NECESSARY FILES AND COMPILE SOURCES WITH FIELD-IMAGE MACRO
;
; COPY FILES FROM DSKB:[10,7] AND USE PRIVATE "SYS:"
.RU DSK:PIP[10,7]
*/X_DSK:[10,7]PIP.SHR,COMPIL.SHR,MACRO.SHR,CREF.SHR
*/X_DSK:[10,7]HELPER.REL
*/X=DSK:[10,7]LINK.SHR,LNK???.SHR
; 
; MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (ERROR)	;TOO BAD
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SHR+*.REL
.ASSIGN DSK: SYS:
; GET A DIRECTORY OF THE AVAILABLE SOURCES
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=MACRO.MAC,MACRO.HLP,MCR???.RND
.IF (ERROR)		; HO HUM
;
; COMPILE MACRO PRODUCING REL FILE ONLY
.COMPILE MACRO /COMPILE
.IF (ERROR) .GOTO ERR1
.GOTO LAB1
LAB1::.CHKPNT LAB1
;
; LOAD NEW RELS AND SAVE THEM
;
.ASSIGN DSK REL
.IF (ERROR) ;SO WE LOAD [10,7] VERSION
.R LINK
*MACRO,HELPER/G
.SSAV DSK:MACRO
.VERSION
.IF (ERROR) .E 137
; 
; TRY IT JUST TO MAKE SURE IT WORKS
.R MACRO
*/H
;
; TRANSFER FILES USING TEMPORARY NAMES
;
.R PIP
*XMACRO.SHR_MACRO.SHR
.GOTO LAB7
LAB7:: .CHKPNT LAB7
;
; NOW, LET'S DO IT AGAIN WITH THE NEW VERSIONS
; 
; COMPILE, LOAD, AND SAVE MACRO PRODUCING CREF AND MAP FILES
.LOAD /LINK /MAP:LPT:MACRO MACRO %"CONTEN:ZERO" /COMPILE/CREF
.IF (ERROR) .GOTO ERR1
.SSAV DSK:MACRO		; THIS IS THE NEW MACRO
.VERSION
.IF (ERROR) . E 137
.GOTO LAB4
LAB4:: .CHKPNT LAB4
; TRY IT JUST TO MAKE SURE IT WORKS
.R MACRO
*/H
; 
; OK, NOW FOR COMPARISON
;
.RUN DSK:FILCOM[10,7]
*=MACRO.SHR,XMACRO.SHR
;
.RU DSKB:DIRECT[10,7]
*XMAC.TMP=MACRO.SHR/CHECK
*XMACRO.TMP=XMACRO.SHR/CHECK
.RU DSKB:TECO[10,7]
=0U1ERXMAC.TMP!CON!Y_>!LOOP!1A-32"ECOLOOP'Q1"E\U1ERXMACRO.TMPOCON'
=13I10I.-2,.T-2D\-Q1"N0LI? L2R'I COMPARISON
=13I10IHT
.IF (ERROR) .PLEASE DIFFERENCES EXIST BETWEEN PRODUCTION VERSIONS OF MACRO
.DELETE X?????.TMP		; DELETE TMP FILES
.GOTO LAB8
LAB8:: .CHKPNT LAB8
; PRODUCE SOURCE LISTINGS AND TELL OPERATOR
.R CREF
*LPT:MACRO=MACRO
.IF (ERROR) .PLEASE CAN'T CREF MACRO.CRF
; 
.PLEASE ASSEMBLY LISTINGS MUST BE LISTED MANUALLY FROM YOUR AREA
;
; GET CHECKSUMMED DIRECTORY OF ALL FILES TO BE SUBMITTED FOR RELEASE
;
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=MACRO.*,*.DOC,*.RND,*.COR
.IF (ERROR)		; NICE TRY
;
.GOTO END


;
ERR1::.PLEASE COMPILATION ERRORS EXIST IN MACRO - ABORTING
.GOTO FEND
END:: .GOTO EEND
FEND:: .GOTO EEND
EEND::.DELETE MACRO.REL,XMACRO.*
.IF (ERROR)	; DON'T CARE IF FAILED
.DELETE LINK.SHR,LNK???.SHR
;.IF (ERROR)	; MUMBLE
.DELETE COMPIL.SHR,PIP.SHR,CREF.SHR,HELPER.REL
.IF (ERROR)	; MUMBLE

