;TO MAKE MTCOPY.SAV FROM MTCOPY.MAC
;
;REQUIRED FILES:
;	[10,7]
;		MACRO.SHR
;		PIP.SHR
;		COMPIL.SHR
;		LINK.SHR
;		LNK???.SHR
;		C.MAC
;		HELPER.REL
;	[SELF]
;		MTCOPY.MAC
;		MTCOPY.HLP
;		MTY?.RND
;OUTPUT:
;		MTCOPY.SAV
;		MTCOPY.LOG
;		MTCOPY.DOC
;
.SET WAT VER
.R PIP[10,7]
*/X_[10,7]C.MAC,HELPER.REL,COMPIL.SHR,MACRO.SHR,LINK.SHR,LNK???.SHR,PIP.SHR
;
.AS DSK SYS
;MAKE U.TMP TO FORCE UNIVERSAL C
.COPY U.MAC=TTY:
	%.C==-3

;COMPIL AND LOAD MTCOPY.MAC PRODUCING MTCOPY.SAV
;
.LOAD/COM U.MAC+C.MAC,MTCOPY.MAC,HELPER.REL %"SEG:LOW"
.IF(ERROR) .GOTO END
.SSAVE DSK:MTCOPY
.VERSION
;
;TRY IT TO MAKE SURE IT WORKS
.RUN MTCOPY
*/H
.GET MTCOPY
.CORE
;NOW LET US SEE IF WE CAN MAKE A DOC FILE WITH RUNOFF
.COPY MTCOPY.RND=MTY?.RND
.RU RUNOFF [10,7]
*MTCOPY.RND
*MTCOPY.DOC
;
.DEAS SYS
;GET CHECKSUMS
.DIR/CHE MTCOPY.*,MTY?.RND
END::
.DEL LINK.SHR,LNK???.SHR,C.*,HELPER.REL,MACRO.SHR,COMPIL.SHR,PIP.SHR

