;JOB%1(21) TO MAKE SCAN.REL,SCANDM.REL FROM SCAN.MAC,SCANDM.MAC
;SUBMIT WITH COMMAND  .QUEUE I:=SCAN/RESTART:1
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	CREF.SHR
;	C.MAC
;[SELF]	SCAN.MAC
;	SCANDM.MAC
;	SCNMAC.MAC
;
;OUTPUT FILES:
;	SCAN.REL
;	SCANDM.REL
;	SCNMAC.MAC	[SAME AS INPUT]
;OUTPUT LISTINGS:
;	SCNMAC CREF LISTING
;	SCAN  CREF LISTING
;	SCANDM CREF LISTING
;	SCAN.LOG
;
;
;COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7]
*/X_DSK:CREF.SHR[10,7],C.MAC[10,7]
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SHR
.GOTO A
A:.RUN DSK: DIRECT[10,7]
*TTY:/CHECKSUM=SCAN.MAC+SCNMAC.MAC+SCN???.RND+SCAN.CTL+SCANDM.MAC
.ASSIGN DSK: SYS:
;
;MAKE U.MAC TEMP FILE TO FORCE UNIVERSALS OF C AND SCNMAC
.COPY U.MAC=TTY:U
*%.C==-3		;FORCE UNIVERSAL FILE
^Z
;COMPILE, PRODUCING CREF FILE
.COMPILE  /COMPILE U.MAC+C.MAC(P,,),U.MAC+SCNMAC.MAC(P,,),SCAN.MAC(P,,), SCANDM.MAC(P,,)
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=SCAN.REL,SCANDM.REL
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.R CREF
*SCNMAC
*SCAN
*SCANDM
.PLEASE SCAN SUCCESSFUL
;
;REMOVE ALL TEMPORARY FILES
%FIN: .DELETE MACRO.SHR,CREF.SHR,COMPIL.SHR,PIP.SHR,C.MAC,U.MAC,C.REL,C.CRF,SCNMAC.REL
