;JOB%1(20) TO MAKE WILD.REL FROM WILD.MAC
;SUBMIT WITH COMMAND  .QUEUE I:=WILD/RESTART:1
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	CREF.SHR
;	C.MAC
;	SCNMAC.MAC
;[SELF]	WILD.MAC
;
;OUTPUT FILES:
;	WILD.REL
;OUTPUT LISTINGS:
;	WILD  CREF LISTING
;	WILD.LOG
;
;
;COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7]
*/X_DSK:CREF.SHR[10,7],C.MAC[10,7],SCNMAC.MAC[10,7]
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SHR
.GOTO A
A:.RUN DSK: DIRECT[10,7]
*TTY:/CHECKSUM=WILD.MAC+C.MAC+SCNMAC.MAC+WLD???.RND+WILD.CTL
.ASSIGN DSK: SYS:
;
;MAKE U.MAC TEMP FILE TO FORCE UNIVERSALS OF C AND SCNMAC
.COPY U.MAC=TTY:
*%.C==-3

;COMPILE, PRODUCING CREF FILE
.COMPILE /CREF /COMPILE U.MAC+C.MAC,U.MAC+SCNMAC.MAC,WILD.MAC
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=WILD.REL
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.ASSIGN DSK LPT
.CREF
.COPY WILD.TMP=WLD???.RND
.RUN RUNOFF[10,7]
*WILD.TMP
*WILD.DOC
.DEAS
.MOUNT DTA:D/VID:'WILD SUBMISSION TAPE'/WE
.IF (ERROR) .GO TO NOTAP
.ZERO D:
.LABEL D:WILD
.COPY D:=WILD.CTL,WILD.MAC,WILD.REL,WLD???.RND
.DIR D:
.DEAS
.PLEASE OPR - GET A DIRECTORY OF DTA:D AND DISMOUNT 
NOTAP::
.PLEASE WILD SUCCESSFUL
;
;REMOVE ALL TEMPORARY FILES
%FIN: .DELETE MACRO.SHR,CREF.SHR,COMPIL.SHR,PIP.SHR,C.MAC,SCNMAC.MAC
.PRI /DISP:RENAME WILD.LST,WILD.LOG/DIS:DEL,/COP:3 WILD.DOC
.K/F
