BEGIN
EXPR FOO(A);  PRINT(A);
EXPR FOO2(A); BEGIN PRINT(A); RETURN 'FOO2OK; END;
EXPR FOO22(A); BEGIN PRINT(A);
  RETURN '(FOO2OK); END;
EXPR FOO23(A); BEGIN NEW B; B_'(THIS IS A LINE); END;
EXPR FOO3(A); BEGIN NEW B; B_'(THIS IS A LINE);
  PRINT A CONS B; PRINT(A); RETURN(CONS( 'OK, CAR(B)));
  PRINT A CONS B; PRINT(A); RETURN ( 'OK CONS CAR(B));
 END;
EXPR FOOO8(L);  BEGIN L[2]; L[1,2]; END;
END.
