;ORIGINAL CODE BY LARSON@ECL
;ADDITIONS BY LIEB@SUMEX
;ADDITIONS BY MOUTON@SRI
;ADDITIONS BY UNTULIS@SRI
;additions of 131 stuff by lieb@sumex

MAJORV==2	;VERSION 2 IS THE MULTIFORK
MINORV==4

TNX131==1	;1=WE HAVE TO LIVE WITH 1.31 TENEX
LPTLOG==0	;LOG FILE DEFAULT IS CTL.LOG
SRIHED==1	;PRINT FILE NAMES AS HEADER 
STRACT==1   	;STRING ACCOUNTS
SRIMSG==1	;SRI MESSAGE SENDING CODE
SKUSER==1	;FORCE BATCH JOBS TO QUEUE 2
SRINOT==1	;SRI NOTIFICATION FLAG
SRISYS==1	;CHOICE IN GETTING LOAD AV
SRIPTY==0	;FIND PSEUDOTTY'S AT SRI
DUMPFG==-1	;0 = DON'T DUMP, -1 = DUMP IMAGE

PTYRNG==-10,,101	;RANGE OF PTY'S

GDDT==0		; DON'T GET DDT
DBGFIL==0	; DEBUG FILE

DEFRTM==^D60*^D1000*^D10	;DEFAULT RUNTIME IS 10 MIN!!!(HE WANTS IT)
DEFETM==^D60*^D60*^D1000*^D12	;DEFAULT CONNECT TIME IS 12 HRS
DEFLLN==^D1000			;DEFAULT LOG LINES IS 1000

IFE DBGFIL, <DBUGFG==1>	;RELOAD INSTEAD OF RESTART
IFN DBGFIL, <DBUGFG==2>	;RELOAD FROM <BATCH>TBATCON.SAV

;QUEUE ENTRY FORMAT DESCRIPTIONS
;THE FOLLOWING ARE THE DISPLACEMENTS FOR THE DIFFERENT
;DATA FIELDS IN A QUEUE ENTRY

QQQ==0					;START VALUE FOR COUNTER

	DEFINE	QE(NAM,LEN<1>)<
NAM==QQQ				;ASSIGN VALUE
QQQ==QQQ+LEN				;ADJUST COUNTER
	>				;END MACRO

	QE(USRDIR)			;DIRECTORY NUMBER OF USER TO LOG
					;JOB IN UNDER
	IFNDEF	STRACT,<
	QE(USRACT)			;ACCT # TO USE WITH LOGIN
	>
	IFDEF	STRACT,<
	QE(USRACT,8)			;ACCT STRING TO USE WITH LOGIN ***SRI-AIC***
	>
	QE(PRIOR)			;PRIORITY FLAG (.LE.0 - BATCH)
	QE(STRTED)			;ID OF THE BATCON WHO STARTED IT
	QE(JOBSTT)			;TIME THIS BATCH JOB WAS STARTED
	QE(RESTRT)			;USER RESTART COUNT
	QE(ENTERD)			;TIME JOB SUBMITTED
	QE(AFTER)			;TIME JOB MUST RUN AFTER
	QE(LOADAV)			;LOAD AVERAGE BELOW WHICH JOB CAN BE STARTED
	QE(ETIME)			;MAXIMUM ELAPSED TIME JOB CAN RUN
	QE(RTIME)			;MAXIMUM CPU TIME JOB CAN RUN
	QE(LOGLNS)			;MAX # LINES JOB CAN WRITE ON LOG FILE
	QE(MESAG)			;SEND MESSAGE TO SUBMITTER FLAG
	QE(NOTFY)			;SEND NOTIFY MESSAGE TO SUBMITTER
	QE(BJOBNO)		;BATCH-JOB NUMBER
	QE(CTLFIL,^D26)			;NAME (<DIR>NAM.EXT;VERS) OF CTL FILE
	QE(LOGFIL,^D26)			;NAME OF LOG FILE

QESIZE==QQQ				;LENGTH OF A QUEUE ENTRY

	PURGE	QE,QQQ			;DON'T NEED THESE ANYMORE

	LALL				;NOW WE WANT TO SEE EXPANSIONS
;AC DEFINITIONS
F==0
A==1
B==2
C==3
D==4
E==5
P=17

FDBVER==7			;VERSION NUMBER IN FDB
FDBUSW==24			;USER SETTABLE WORD

;OPDEFS
OPDEF	QOPENF	[PUSHJ P,.OPENF]		;RETRIES OPENING FILES

;MACRO DEFINITIONS
	DEFINE OPENM<
	PUSH	P,A			;SAVE JFN
	PUSH	P,C			;GET A REGISTER FOR COUNTING
	MOVEI	C,^D20			;MAXIMUM NUMBER OF RETRIES
OPENF1:	OPENF				;TRY IT
	JRST	OPENF4
OPENF2:	
	AOS	-2(P)			;SKIP RETURN
OPENF3:	
	POP	P,C			;RESTORE REGS
	SUB	P,[1,,1]		;GET JFN OFF STACK
	POPJ	P,
OPENF4:	
	CAIE	A,OPNX9			;BUSY?
	JRST	OPENF3			;NO, RETURN +1
	MOVEI	A,^D30K			;30 SECOND DELAY
	DISMS
	MOVE	A,-1(P)			;GET BACK JFN
	SOJG	C,OPENF1		;TRY AGAIN IF ANY RETRIES LEFT
	JRST	OPENF3			;ELSE RETURN +1
>

	DEFINE CRSHUS<			;;STRING POINTERS OF PERSONS TO RECEIVE CRASH MESSAGES
IFE DBGFIL,<
	POINT 7,[ASCIZ /LIEB/]
	POINT 7,[ASCIZ /CROSSLAND/]
	POINT 7,[ASCIZ /COWER/]
>
IFN DBGFIL,<
	POINT 7,[ASCIZ /LIEB/]
>
>
